fix(css): font, reload, update next to 13
thunderTheGun/tak-psychologist-page pull request #13
Opened 2023-05-16 16:52 UTC by mikitovicsmark

update to next 13
fixed:
- fonts
- reload - css
- eslint

2023-05-17 19:13 UTC, thunderTheGun requested changes

2023-05-17 19:13 UTC, thunderTheGun commented on components/AboutMe/molecules/PictureOnShapesDesktop.tsx
> +import Image from 'next/legacy/image';
is there a new Image on the block? 😲

2023-05-17 19:13 UTC, thunderTheGun commented on components/Footer/Footer.tsx
> +  <BackgroundWrapper bgColor={Green010}>
This is sort of a nitpicking, but I'd rather use full names, e.g. backgroundColor

2023-05-17 19:13 UTC, thunderTheGun commented on components/Footer/Form/atoms/DropDownIndicator.tsx
> +  const Indicator = components.DropdownIndicator;
yep, I like it better like this too

2023-05-17 19:13 UTC, thunderTheGun commented on components/Footer/Form/Form.styles.tsx
> +import { Figtree } from 'next/font/google';
locally this breaks on my computer:

![image](https://github.com/thunderTheGun/tak-psychologist-page/assets/89024435/bb4d2fa2-0f0d-481b-877b-672a163469ce)

2023-05-17 19:13 UTC, thunderTheGun commented on components/NavBar/organisms/NavBar.tsx
> +      setIsMobile(window.innerWidth < 1200);
I think this solution does not work on window resize. On the Vercel deployment it does not, as I see.

2023-05-17 19:13 UTC, thunderTheGun commented on components/WhatICanHelpYouWith/molecules/Unit.tsx
> +  const ItemIcon = item.icon;
I may not see exactly why this was changed. If item.icon had been used at least 2 times below I would absolutely agree. Dot notation is used anyway at other places below.

2023-05-17 19:13 UTC, thunderTheGun commented on components/WhatICanHelpYouWith/molecules/Unit.tsx
> +          {item.title}
See my comment on line 25. This is an example on using dot notation anyway.

2023-05-17 19:13 UTC, thunderTheGun commented on components/WhatICanHelpYouWith/organisms/WhatICanHelpYouWith.tsx
> +  <BackgroundWrapper bgColor={Blue010}>
yepp, I didn't notice this rogue empty component.

2023-05-17 19:13 UTC, thunderTheGun commented on components/atoms/PsychoLink.tsx
> -const StyledLink = styled.a`
note to self: I vaguely remember why this was needed, need to check out if all links are as per design

2023-05-17 19:13 UTC, thunderTheGun commented on pages/blog.tsx
> +    <BackgroundWrapper>
I do not see why, but this still seems to work on Vercel. But really, why? 😄

2023-05-18 09:53 UTC, mikitovicsmark commented on components/AboutMe/molecules/PictureOnShapesDesktop.tsx
> +import Image from 'next/legacy/image';
yup, the old one runs as legacy now

2023-05-18 09:53 UTC, mikitovicsmark commented on components/Footer/Footer.tsx
> +  <BackgroundWrapper bgColor={Green010}>
agreed

2023-05-18 09:55 UTC, mikitovicsmark commented on components/WhatICanHelpYouWith/molecules/Unit.tsx
> +  const ItemIcon = item.icon;
the same reason i changed it in the dropdownIndicator - to capitalise component names, and make the template a bit readable

2023-05-18 09:56 UTC, mikitovicsmark commented on components/WhatICanHelpYouWith/molecules/Unit.tsx
> +          {item.title}
see my previous comment

2023-05-18 09:57 UTC, mikitovicsmark commented on components/atoms/PsychoLink.tsx
> -const StyledLink = styled.a`
probably because older next links needed an a tag inside, now they don't require it

2023-05-18 09:57 UTC, mikitovicsmark commented on pages/blog.tsx
> +    <BackgroundWrapper>
Because the BackgroundWrapper has a default grey010 if none is provided.

2023-05-18 10:01 UTC, mikitovicsmark commented on components/Footer/Form/Form.styles.tsx
> +import { Figtree } from 'next/font/google';
try a clean install plz, maybe the nextjs update messed something up on your side. works fine on my end

2023-05-18 10:01 UTC, mikitovicsmark commented on components/NavBar/organisms/NavBar.tsx
> +      setIsMobile(window.innerWidth < 1200);
yup, going to fix it

2023-05-18 10:19 UTC, thunderTheGun commented on components/atoms/PsychoLink.tsx
> -const StyledLink = styled.a`
okay, and everything seems cool

2023-05-18 12:30 UTC, thunderTheGun approved these changes

2023-05-18 13:37 UTC, merged